In [69]:
import numpy as np

In [70]:
X = np.array([
[1, 1, 0,0],
[0, 0, 0,1],
[1, 0, 0,0],
[0, 0, 1,1]])

alpha=0.6

In [71]:
#w=np.random.random((len(X[0]),2))
w=[]
w.append([0.2,0.8])
w.append([0.6,0.4])
w.append([0.5,0.7])
w.append([0.9,0.3])
w=np.array(w)
print(w)

[[ 0.2  0.8]
 [ 0.6  0.4]
 [ 0.5  0.7]
 [ 0.9  0.3]]


In [72]:
print(w[:,0])
print(X[0])

[ 0.2  0.6  0.5  0.9]
[1 1 0 0]


In [73]:
epoch=100
distance=[]


def dist(x):
    distance2=[]
    for l in range(0,2):
        s=0
        W=w[:,l]
        for k in range(0,4):
            #print(x[k])
            #print(W[k])
            d=np.power((x[k]-W[k]),2)
            #print(d)
            s=s+d
        #print(s)
        distance.append(s)
        distance2.append(s)
        
    return distance2


for i in range(0,epoch):
    print("Learning Rate=",alpha)
    for j in range(0,4):
        x=X[j]
        element=(dist(x))
        m=99999999999
        print(element)
        for j in range(0,2):
            if element[j]<m:
                m=element[j]
                key=j
        uw=w[:,key]
        for p in range(0,len(uw)):
            w[p][key]=w[p][key]+alpha*(x[p]-w[p][key])


        #print(w)
        
    alpha=alpha/2
    
            
    

#print(distance)
print(w)

        

Learning Rate= 0.6
[1.8600000000000003, 0.97999999999999987]
[0.66000000000000003, 2.2767999999999997]
[1.8655999999999997, 0.67679999999999996]
[0.70560000000000023, 2.724288]
Learning Rate= 0.3
[3.1848960000000002, 0.50028799999999995]
[0.47289599999999993, 2.1587411200000002]
[2.1645190400000001, 0.27074112000000011]
[0.27971904000000003, 2.9445031488]
Learning Rate= 0.15
[3.2623423296, 0.41474314879999996]
[0.4034623296, 2.143243925008]
[2.251517533136, 0.20988392500800007]
[0.21506153313599996, 3.01569553581828]
Learning Rate= 0.075
[3.26839675769076, 0.3779439358182799]
[0.37035595769076002, 2.1366524900845159]
[2.2854483962991567, 0.1890481900845159]
[0.19303486629915653, 3.0454359036410636]
Learning Rate= 0.0375
[3.2674887457272161, 0.36100969089106383]
[0.35472758622721584, 2.1335098290426746]
[2.3006327249345562, 0.18015837569892468]
[0.18366830400643167, 3.0591417024613943]
Learning Rate= 0.01875
[3.2663506485138099, 0.3528974813059646]
[0.347169255595763, 2.1319703452192131

In [74]:
ww=w
for h in range(0,4):
    for q in range(0,2):
        if(ww[h][q]<0.09):
            ww[h][q]=0
        elif ww[h][q]>0.1 and ww[h][q]<0.80:
            ww[h][q]=0.5
        else:
            ww[h][q]=1

print(ww)

    
        

[[ 0.   1. ]
 [ 0.   0.5]
 [ 0.5  0. ]
 [ 1.   0. ]]


In [77]:
w=ww
cluster=[]
for j in range(0,4):
        x=X[j]
        m=99999999999
        element=dist(x)
        #print(element)
        for j in range(0,2):
            if element[j]<m:
                m=element[j]
                key=j
        cluster.append(key+1)
print(cluster)
        
        

[3.25, 0.25]
[0.25, 2.25]
[2.25, 0.25]
[0.25, 3.25]
[2, 1, 2, 1]


In [82]:
cluster=np.array(cluster)
cluster=cluster.reshape(4,1)
output=np.concatenate((X, cluster), axis=1)
print(output)

[[1 1 0 0 2]
 [0 0 0 1 1]
 [1 0 0 0 2]
 [0 0 1 1 1]]
