In [28]:
import numpy as np
from matplotlib import pyplot as plt

def sigmoid(x, derive=False):
    if derive:
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))

# Define the data set XOR
X = np.array([
    [1, 1, 1],
    [1, 0, 1],
    [0, 1, 1],
    [0, 0, 1],
])

y = np.array([[0],
              [1],
              [1],
              [0]
             ])

# Define a learning rate
eta = 0.5
# Define the number of epochs for learning
epochs = 50000

# Initialize the weights with random numbers
w01 = np.random.random((len(X[0]), 5))
w12 = np.random.random((5, 1))
print(w01)
print(w12)

[[ 0.33818006  0.86465314  0.06245453  0.25938684  0.61921065]
 [ 0.31887835  0.29771713  0.76713359  0.95896444  0.87222974]
 [ 0.63998708  0.79095628  0.82255275  0.18647833  0.32397217]]
[[ 0.06333302]
 [ 0.40274787]
 [ 0.95826144]
 [ 0.84820208]
 [ 0.73500183]]


In [3]:
    z_h = np.dot(X, w01)
    print("Z_h=",z_h)
    a_h = sigmoid(z_h)
    print("a_h=",a_h)

Z_h= [[ 1.16089356  0.78996619]
 [ 0.66854822  0.24032131]
 [ 0.76767187  0.65979681]
 [ 0.27532653  0.11015193]]
a_h= [[ 0.76149504  0.68782407]
 [ 0.66117801  0.55979283]
 [ 0.68301706  0.65921474]
 [ 0.56840009  0.52751017]]


In [6]:
    z_o = np.dot(a_h, w12)
    print("Z_o=",z_o)
    a_o = sigmoid(z_o)
    print("a_o=",a_o)

Z_o= [[ 0.55821263]
 [ 0.47822088]
 [ 0.50797677]
 [ 0.41909684]]
a_o= [[ 0.63603888]
 [ 0.61732767]
 [ 0.62433206]
 [ 0.60326711]]


In [7]:
a_o_error = ((1 / 2) * (np.power((a_o - y), 2)))
print("a_o_error=",a_o_error)

a_o_error= [[ 0.20227273]
 [ 0.07321906]
 [ 0.0705632 ]
 [ 0.1819656 ]]


In [12]:
# Backpropagation
    ## Output layer
delta_a_o_error = a_o - y
print("delta_a_o_error=",delta_a_o_error)
delta_z_o = sigmoid(a_o,derive=True)
print("delta_z_o=",delta_z_o)
delta_w12 = a_h
print("delta_w12=",delta_w12)
st=(delta_z_o*delta_a_o_error)
print(st)
delta_output_layer = np.dot(delta_w12.T,(delta_a_o_error * delta_z_o))
dEw=np.dot(delta_w12.T,st)
print("delta_output_layer=",delta_output_layer)
print("dEw=",dEw)
    

delta_a_o_error= [[ 0.63603888]
 [-0.38267233]
 [-0.37566794]
 [ 0.60326711]]
delta_z_o= [[ 0.23149342]
 [ 0.23623422]
 [ 0.23454154]
 [ 0.2393359 ]]
delta_w12= [[ 0.76149504  0.68782407]
 [ 0.66117801  0.55979283]
 [ 0.68301706  0.65921474]
 [ 0.56840009  0.52751017]]
[[ 0.14723882]
 [-0.0904003 ]
 [-0.08810974]
 [ 0.14438348]]
delta_output_layer= [[ 0.07423807]
 [ 0.06874948]]
dEw= [[ 0.07423807]
 [ 0.06874948]]


In [13]:
w12 = w12 - eta * delta_output_layer
print(w12)

[[ 0.35453044]
 [-0.03375711]]


In [16]:
delta_a_h = np.dot(delta_a_o_error * delta_z_o, w12.T)
print("delta_a_h",delta_a_h)
dEdah=np.dot(st,w12.T)
print("dEdah=",dEdah)

delta_a_h [[ 0.05220064 -0.00497036]
 [-0.03204966  0.00305165]
 [-0.03123758  0.00297433]
 [ 0.05118834 -0.00487397]]
dEdah= [[ 0.05220064 -0.00497036]
 [-0.03204966  0.00305165]
 [-0.03123758  0.00297433]
 [ 0.05118834 -0.00487397]]


In [17]:
delta_z_h = sigmoid(a_h,derive=True)
print("delta_z_h",delta_z_h)
dahdzh=sigmoid(a_h,derive=True)
print("dahdzh=",dahdzh)

delta_z_h [[ 0.18162034  0.21472212]
 [ 0.22402165  0.24642482]
 [ 0.21650476  0.22465067]
 [ 0.24532143  0.24924319]]
dadzh= [[ 0.18162034  0.21472212]
 [ 0.22402165  0.24642482]
 [ 0.21650476  0.22465067]
 [ 0.24532143  0.24924319]]


In [19]:
delta_w01 = X
delta_hidden_layer = np.dot(delta_w01.T, delta_a_h * delta_z_h)
fs=delta_a_h * delta_z_h
print("fs=",fs)
dEdw1=np.dot(delta_w01.T,fs)
print("delta_hidden_layer",delta_hidden_layer)
print("dEdw1",dEdw1)

fs= [[ 0.0094807  -0.00106725]
 [-0.00717982  0.000752  ]
 [-0.00676309  0.00066819]
 [ 0.0125576  -0.0012148 ]]
delta_hidden_layer [[ 0.00230088 -0.00031524]
 [ 0.00271761 -0.00039906]
 [ 0.00809539 -0.00086186]]
dEdw1 [[ 0.00230088 -0.00031524]
 [ 0.00271761 -0.00039906]
 [ 0.00809539 -0.00086186]]


In [20]:
w01 = w01 - eta * delta_hidden_layer
print(w01)

[[ 0.38631905  0.13111511]
 [ 0.4841925   0.55084206]
 [ 0.25104035  0.11273751]]


In [29]:
for epoch in range(epochs):
    # Feed forward
    z_h = np.dot(X, w01)
    a_h = sigmoid(z_h)

    z_o = np.dot(a_h, w12)
    a_o = sigmoid(z_o)

    # Calculate the error
    a_o_error = ((1 / 2) * (np.power((a_o - y), 2)))

    # Backpropagation
    ## Output layer
    delta_a_o_error = a_o - y
    delta_z_o = sigmoid(a_o,derive=True)
    delta_w12 = a_h
    delta_output_layer = np.dot(delta_w12.T,(delta_a_o_error * delta_z_o))

    ## Hidden layer
    delta_a_h = np.dot(delta_a_o_error * delta_z_o, w12.T)
    delta_z_h = sigmoid(a_h,derive=True)
    delta_w01 = X
    delta_hidden_layer = np.dot(delta_w01.T, delta_a_h * delta_z_h)

    w01 = w01 - eta * delta_hidden_layer
    w12 = w12 - eta * delta_output_layer
print(w01)
print(w12)

[[-2.61700493  7.41806243  1.21810333  1.76026892  6.28782391]
 [ 6.80323767 -4.31214165  3.15237529  1.85702512  6.26520984]
 [-0.29468228  1.17051979 -3.000712    1.68243252 -1.54867468]]
[[ -7.9100769 ]
 [ -9.52492982]
 [ -3.93863701]
 [  3.33900035]
 [ 12.23878377]]


In [30]:
test_a_h=sigmoid(np.dot(X,w01));
prediction=sigmoid(np.dot(test_a_h,w12))
print(prediction)


[[ 0.00878656]
 [ 0.9923848 ]
 [ 0.99306249]
 [ 0.00280869]]
