In [49]:
import numpy as np

In [50]:

data=np.random.randint(2,size=(100,10))
#print(data)
extra=np.ones((100,1),dtype=int)
#print(extra)
X= np.concatenate((data, extra), axis=1)
print(X)

[[0 0 0 ..., 0 0 1]
 [1 1 1 ..., 1 1 1]
 [1 1 1 ..., 1 0 1]
 ..., 
 [0 0 0 ..., 0 1 1]
 [1 0 1 ..., 1 0 1]
 [1 0 0 ..., 0 0 1]]


In [51]:
ans=[]
for i in range(0,100):
  res=0
  for j in range(0,10):
      #print((X[i][j]), end = '')
      res=abs(X[i][j]-res)
  #print("")
  ans.append(res)
y=np.reshape(ans,(100,1))
print(y)
      

[[1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]]


In [52]:
w1=np.random.random((len(X[0]),5))
w2=np.random.random((5,1))
print(w1)
print(w2)

[[ 0.14336409  0.8758594   0.67721276  0.14157472  0.07097049]
 [ 0.08825601  0.9295021   0.23503341  0.52316414  0.49684062]
 [ 0.65156915  0.19445803  0.16495654  0.48513321  0.270603  ]
 [ 0.39020671  0.88495705  0.13439449  0.00594989  0.73064113]
 [ 0.89063763  0.52443572  0.96978608  0.71381424  0.97218434]
 [ 0.55839627  0.82038705  0.9604905   0.70359528  0.47902248]
 [ 0.15770677  0.31191094  0.71683907  0.40526019  0.14063807]
 [ 0.6630934   0.90647895  0.56720253  0.79824154  0.36827408]
 [ 0.83865698  0.48211146  0.77771008  0.95636809  0.98928041]
 [ 0.33056284  0.339833    0.82352848  0.27188177  0.56760554]
 [ 0.8863534   0.71276265  0.50998069  0.57098128  0.71217348]]
[[ 0.46842833]
 [ 0.83171671]
 [ 0.35079485]
 [ 0.25682616]
 [ 0.56437658]]


In [53]:
def sigmoid(x, deriv=False):
  if(deriv):
    return x*(1-x)
  else:
    return (1/(1+np.exp(-x)))

In [54]:
for epoch in range(0,80000):
  
  eta=0.5
  #Weighted Sum

  z_h=np.dot(X,w1)
  a_h=sigmoid(z_h)
  
  # second weighted sum
  z_o=np.dot(a_h,w2)
  a_o=sigmoid(z_o)
  #Error Calculate
  Ea=(0.5*(np.power((a_o-y),2)))
  #BackPropagation dE/dw2
  #dE/da0
  dEda0=(a_o-y)
  #da0/dz0
  da0dz0=sigmoid(a_o,deriv=True)
  #dz0/dw
  dz0dw=a_h
  #dE/dw2
  st=da0dz0*dEda0
  dEdw2=np.dot(dz0dw.T,st)
  #Weight update
  w2=w2-(eta*dEdw2)
  #hidden Layer dEdw1
  #dE/dah
  dEdah=np.dot(st,w2.T)
  #dzh/dw
  dzhdw=X
  #dah/dzh
  dahdzh=sigmoid(a_h,deriv=True)
  fs=dEdah*dahdzh
  dEdw1=np.dot(dzhdw.T,fs)
  #Weight Update
  w1=w1-(eta*dEdw1)
 
print(w1)
print(w2)
  

[[ -1.0880761    1.23842798   9.86625784 -11.78629979  -2.73220032]
 [ -8.12638012  14.03613493   5.41262056   1.76900685   6.61330121]
 [ -4.27168473  10.12678455   3.51811075   8.34357043  -2.80381479]
 [  1.36124981   4.65628926   1.61646366  18.45034767   7.08577906]
 [  7.53750206  -3.89688405  16.23838814  34.84578095  14.50454852]
 [  2.6651813   -0.46788839   2.37046263 -15.06146386  -5.91676727]
 [  2.14416529  -3.66244546   3.32398546  -8.53496844  -9.72614855]
 [  7.8736044   -5.77875271 -11.2125851   -4.10154989  -1.44939493]
 [ -3.96122431   8.71004998   3.0965552   15.1562257   -1.350864  ]
 [  2.01179805  -5.03934188  -2.49987099   1.63291181   4.80020672]
 [  0.14414209  -6.48051738  -2.56335571 -15.66032652  10.54918139]]
[[ 15.88977424]
 [ 17.98667668]
 [-24.09341537]
 [-20.70238751]
 [ 17.77645357]]


In [55]:
np.set_printoptions(suppress=True)
test_ah=sigmoid(np.dot(X,w1))
prediction=sigmoid(np.dot(test_ah,w2))
print(prediction)

[[ 0.99996833]
 [ 0.99999254]
 [ 0.00012021]
 [ 0.0001388 ]
 [ 0.99430943]
 [ 0.00409566]
 [ 0.99035358]
 [ 0.00843775]
 [ 0.99302747]
 [ 0.00003963]
 [ 0.99993039]
 [ 0.00015518]
 [ 0.99725978]
 [ 1.        ]
 [ 0.99888911]
 [ 0.99999912]
 [ 0.98344695]
 [ 0.01935376]
 [ 0.99999994]
 [ 0.0039429 ]
 [ 0.00311552]
 [ 0.99997632]
 [ 0.99758812]
 [ 0.01198   ]
 [ 0.00019876]
 [ 0.99999147]
 [ 0.98349271]
 [ 0.99999737]
 [ 0.00012025]
 [ 0.99852609]
 [ 0.00053289]
 [ 0.00730437]
 [ 0.00313969]
 [ 0.00149928]
 [ 0.99999978]
 [ 0.0120979 ]
 [ 0.00001726]
 [ 0.00168278]
 [ 0.00020408]
 [ 0.98609842]
 [ 0.006263  ]
 [ 0.00006885]
 [ 0.00014168]
 [ 0.00001515]
 [ 0.99999999]
 [ 0.98751536]
 [ 0.00127719]
 [ 0.00736201]
 [ 0.00001482]
 [ 0.00001472]
 [ 0.99999978]
 [ 0.9894154 ]
 [ 0.99987961]
 [ 0.00530953]
 [ 0.00018136]
 [ 0.01363537]
 [ 0.00001756]
 [ 0.00030417]
 [ 0.99999866]
 [ 0.00002177]
 [ 0.0005085 ]
 [ 0.00233732]
 [ 0.00011975]
 [ 0.00033657]
 [ 0.00616135]
 [ 0.99035358]
 [ 0.99825

In [56]:
result=[]
for i in range(0,100):
    if(prediction[i]>0.90):
        result.append(1)
    else:
        result.append(0)
target=np.reshape(result,(100,1))
print(target)

[[1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]]


In [57]:
#Training Accuracy
cnt=0

for i in range(0,100):
    for j in range(0,1):
        if(target[i][j]==y[i][j]):
            cnt=cnt+1

accuracy=(cnt/100)*100.00
print(accuracy,"%")
    
        

99.0 %
