In [136]:
import numpy as np

In [137]:

data=np.random.randint(2,size=(50,10))
#print(data)
extra=np.ones((50,1),dtype=int)
#print(extra)
X= np.concatenate((data, extra), axis=1)
print(X)

[[1 1 1 1 1 0 0 1 1 0 1]
 [0 0 0 0 0 1 1 1 0 1 1]
 [1 0 1 0 0 0 0 0 0 0 1]
 [0 0 0 1 0 1 0 0 1 0 1]
 [1 1 0 1 0 0 1 1 1 0 1]
 [1 0 1 0 1 1 0 1 1 1 1]
 [1 1 0 0 0 0 1 1 0 0 1]
 [0 0 1 1 1 0 1 0 1 0 1]
 [1 0 0 0 0 1 0 0 0 0 1]
 [0 1 1 0 0 0 0 1 1 1 1]
 [0 0 1 1 0 1 1 0 1 1 1]
 [0 0 1 0 1 0 1 0 1 0 1]
 [1 1 0 1 0 0 0 1 0 0 1]
 [0 1 0 1 1 0 0 0 0 1 1]
 [1 1 1 1 0 0 0 1 1 1 1]
 [0 1 1 1 0 1 0 0 0 0 1]
 [1 1 0 1 1 1 0 1 1 1 1]
 [1 0 1 0 0 0 1 1 0 0 1]
 [1 0 1 1 1 1 1 0 0 1 1]
 [1 0 1 1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 0 1 0 1 1]
 [1 1 0 0 0 0 0 1 0 0 1]
 [1 0 1 1 0 0 1 0 1 0 1]
 [0 1 1 0 0 0 0 1 0 1 1]
 [1 0 0 1 1 0 0 0 1 0 1]
 [1 1 1 1 1 1 1 0 0 1 1]
 [0 0 1 0 1 1 1 0 0 0 1]
 [1 1 0 1 0 1 1 0 0 1 1]
 [0 1 1 0 1 0 0 1 1 1 1]
 [0 0 1 0 0 1 1 1 1 1 1]
 [1 1 1 1 1 1 0 0 0 0 1]
 [0 0 1 1 1 0 0 1 0 1 1]
 [0 0 0 0 1 1 1 1 1 0 1]
 [1 1 1 0 0 1 0 0 0 0 1]
 [1 1 0 1 1 1 0 0 0 0 1]
 [1 1 0 1 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 1 1 1 1]
 [0 1 0 0 1 0 1 1 1 0 1]
 [1 1 1 0 0 1 1 1 0 1 1]
 [0 0 1 0 1 1 0 1 1 0 1]


In [138]:
ans=[]
temp=[]
for i in range(0,50):
  res=0
  for j in range(0,10):
      #print((X[i][j]), end = '')
     res=abs(X[i][j]-res)
     
  #print("")
  re=np.binary_repr(res, width=3)
  temp=[]
  for k in re:
      temp.append(int(k))
      
  ans.append(temp)
y=np.reshape(ans,(50,3))
print(y)
      

[[0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]]


In [139]:
w1=np.random.random((len(X[0]),8))
w2=np.random.random((8,3))
print(w1)
print(w2)

[[ 0.96041155  0.7305858   0.573741    0.3287706   0.14816729  0.42124835
   0.73116154  0.24688401]
 [ 0.93335935  0.04167742  0.13435741  0.10842099  0.26691914  0.22393367
   0.16553155  0.62914112]
 [ 0.90527039  0.0117997   0.19944131  0.65905376  0.81150935  0.59909574
   0.62641796  0.24070094]
 [ 0.81799806  0.13606347  0.63239591  0.05523897  0.35003425  0.60563055
   0.24345542  0.64569588]
 [ 0.93932543  0.94079835  0.3399982   0.12157758  0.51235906  0.19528074
   0.5487068   0.75710793]
 [ 0.04676963  0.31905149  0.74957563  0.39379697  0.06439771  0.17041207
   0.11782728  0.72038092]
 [ 0.57090666  0.77017079  0.28468009  0.00823165  0.00654478  0.76540895
   0.2518093   0.33121744]
 [ 0.95975601  0.20667123  0.51170273  0.65092163  0.11903821  0.57903337
   0.52890889  0.01530145]
 [ 0.88541915  0.01046887  0.13748547  0.51630674  0.90141134  0.07695817
   0.46541319  0.72494209]
 [ 0.30869887  0.99196228  0.20208131  0.41647401  0.66715229  0.4491527
   0.41767305  0.1

In [140]:
def sigmoid(x, deriv=False):
  if(deriv):
    return x*(1-x)
  else:
    return (1/(1+np.exp(-x)))

In [141]:
for epoch in range(0,120000):
  
  eta=0.5
  #Weighted Sum

  z_h=np.dot(X,w1)
  a_h=sigmoid(z_h)
  
  # second weighted sum
  z_o=np.dot(a_h,w2)
  a_o=sigmoid(z_o)
  #Error Calculate
  Ea=(0.5*(np.power((a_o-y),2)))
  #BackPropagation dE/dw2
  #dE/da0
  dEda0=(a_o-y)
  #da0/dz0
  da0dz0=sigmoid(a_o,deriv=True)
  #dz0/dw
  dz0dw=a_h
  #dE/dw2
  st=da0dz0*dEda0
  dEdw2=np.dot(dz0dw.T,st)
  #Weight update
  w2=w2-(eta*dEdw2)
  #hidden Layer dEdw1
  #dE/dah
  dEdah=np.dot(st,w2.T)
  #dzh/dw
  dzhdw=X
  #dah/dzh
  dahdzh=sigmoid(a_h,deriv=True)
  fs=dEdah*dahdzh
  dEdw1=np.dot(dzhdw.T,fs)
  #Weight Update
  w1=w1-(eta*dEdw1)
 
print(w1)
print(w2)
  

[[ 1.53443913  0.77848415  0.20242309 -4.3957388  -0.07088646  4.69306537
   5.5124591   1.49124189]
 [ 1.72231677  9.87984581  0.28414498  4.41699093  1.38037286 -1.28243367
  -5.41016996  2.89408265]
 [-1.83794883 -0.95657591 -0.02197949  6.07306168 -0.01431132  5.33583596
   2.27889765 -5.98738172]
 [ 2.18732109 -6.22238748  0.9626006   1.55565282  1.06281069  5.25147893
  -1.86746938 -0.62420304]
 [ 1.89102681  0.92315543 -1.22610718  2.0870245   0.91555132  4.45391568
  -2.15182678 -0.08332308]
 [-1.05462474  4.83108097  1.06289388  3.80307299  0.65143712 -0.06858119
  -1.70655585  1.49537349]
 [ 0.69929025  6.64824043  1.43859284  0.08216041 -0.41306693  4.31279949
   2.20779879 -2.25230808]
 [ 1.38069114 -5.17601462  0.61519696 -1.03737326  0.30878797 -4.42257502
   1.52221221 -0.66518508]
 [ 0.41869912 -8.20897791 -0.48624318  0.56653722  1.08916954 -4.95877064
  -4.2437061  -2.80922406]
 [ 0.86376618  3.11941172 -0.12213994 -1.20568675  1.1583592   5.25187928
   2.46598791 -3.

In [142]:
np.set_printoptions(suppress=True)
test_ah=sigmoid(np.dot(X,w1))
prediction=sigmoid(np.dot(test_ah,w2))
print(prediction)

[[ 0.00005812  0.00005355  0.99758876]
 [ 0.00007055  0.00005447  0.0000913 ]
 [ 0.00055675  0.00045614  0.00064746]
 [ 0.00030471  0.00034896  0.99999985]
 [ 0.00009206  0.00006501  0.00001547]
 [ 0.00004845  0.00004739  0.99918167]
 [ 0.00005459  0.0000434   0.00125193]
 [ 0.00006799  0.0000623   0.99655237]
 [ 0.0002321   0.00013843  0.00123851]
 [ 0.00012745  0.00012092  0.99794767]
 [ 0.00005154  0.0000333   0.00111256]
 [ 0.00016202  0.00010133  0.00089093]
 [ 0.00004112  0.00002492  0.00154995]
 [ 0.00003179  0.00002159  0.00146   ]
 [ 0.00004379  0.00004126  0.99645684]
 [ 0.00006087  0.00003742  0.00032355]
 [ 0.0000214   0.00001533  0.00207482]
 [ 0.00011423  0.00011743  0.00220205]
 [ 0.00000546  0.00000607  0.99627258]
 [ 0.00009139  0.00011139  0.99992765]
 [ 0.00001725  0.00001268  0.00304308]
 [ 0.00014182  0.00011927  0.9975247 ]
 [ 0.0000595   0.00006494  0.99934788]
 [ 0.00004421  0.00002996  0.00139935]
 [ 0.00042315  0.00031258  0.00339382]
 [ 0.00001551  0.00001164

In [143]:
result=[]
for i in range(0,50):
    tp=[]
    for j in range(0,3):
        if(prediction[i][j]>0.90):
            tp.append(1)
        else:
            tp.append(0)
    result.append(tp)
target=np.reshape(result,(50,3))
print(target)

[[0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]]


In [144]:
#Training Accuracy
cnt=0

for i in range(0,50):
    for j in range(0,3):
        if(target[i][j]==y[i][j]):
            cnt=cnt+1

accuracy=(cnt/150.00)*100.00
print(accuracy,"%")
    
        

100.0 %
