In [45]:
import numpy as np

In [47]:

data=np.random.randint(2,size=(10,10))
#print(data)
extra=np.ones((10,1),dtype=int)
#print(extra)
X= np.concatenate((data, extra), axis=1)
print(X)

[[0 1 0 1 1 1 1 0 0 1 1]
 [1 0 0 1 1 1 1 0 1 1 1]
 [1 1 1 0 1 1 1 0 0 0 1]
 [0 0 1 1 1 0 0 0 1 0 1]
 [0 1 1 0 0 1 1 0 0 1 1]
 [0 1 1 1 0 0 1 1 0 0 1]
 [1 1 0 1 0 1 0 1 0 1 1]
 [1 0 1 0 0 1 0 0 0 0 1]
 [1 1 0 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 1 0 1 0 1]]


In [48]:
ans=[]
temp=[]
for i in range(0,10):
  res=0
  for j in range(0,10):
      #print((X[i][j]), end = '')
     res=abs(X[i][j]-res)
     
  #print("")
  re=np.binary_repr(res, width=3)
  temp=[]
  for k in re:
      temp.append(int(k))
      
  ans.append(temp)
y=np.reshape(ans,(10,3))
print(y)
      

[[0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]]


In [49]:
w1=np.random.random((len(X[0]),8))
w2=np.random.random((8,3))
print(w1)
print(w2)

[[ 0.12586533  0.02770689  0.64044877  0.05750824  0.67757949  0.73618364
   0.22465821  0.14589776]
 [ 0.5059037   0.3706837   0.25331071  0.64175254  0.74858655  0.25735311
   0.69002895  0.67767733]
 [ 0.76365004  0.22987463  0.09260781  0.06857004  0.50531285  0.34254248
   0.33823934  0.01232179]
 [ 0.08944356  0.59757267  0.885773    0.75358192  0.67798634  0.7338829
   0.71692293  0.42166702]
 [ 0.65571514  0.63863021  0.83380084  0.16225863  0.3091504   0.33248155
   0.63573272  0.64124054]
 [ 0.68991206  0.50511738  0.77350171  0.12512952  0.91617953  0.89803621
   0.82369645  0.13436062]
 [ 0.52046508  0.91793668  0.3109408   0.62046702  0.53367402  0.07722165
   0.97333658  0.64768996]
 [ 0.28337592  0.16257915  0.23149833  0.31297909  0.71299112  0.49750477
   0.6842456   0.96628501]
 [ 0.69429094  0.84087343  0.91521573  0.29921159  0.23871599  0.76115983
   0.06190412  0.31621255]
 [ 0.81678726  0.66738907  0.71382737  0.63514529  0.10043474  0.77647933
   0.37191137  0.5

In [50]:
def sigmoid(x, deriv=False):
  if(deriv):
    return x*(1-x)
  else:
    return (1/(1+np.exp(-x)))

In [51]:
for epoch in range(0,120000):
  
  eta=0.5
  #Weighted Sum

  z_h=np.dot(X,w1)
  a_h=sigmoid(z_h)
  
  # second weighted sum
  z_o=np.dot(a_h,w2)
  a_o=sigmoid(z_o)
  #Error Calculate
  Ea=(0.5*(np.power((a_o-y),2)))
  #BackPropagation dE/dw2
  #dE/da0
  dEda0=(a_o-y)
  #da0/dz0
  da0dz0=sigmoid(a_o,deriv=True)
  #dz0/dw
  dz0dw=a_h
  #dE/dw2
  st=da0dz0*dEda0
  dEdw2=np.dot(dz0dw.T,st)
  #Weight update
  w2=w2-(eta*dEdw2)
  #hidden Layer dEdw1
  #dE/dah
  dEdah=np.dot(st,w2.T)
  #dzh/dw
  dzhdw=X
  #dah/dzh
  dahdzh=sigmoid(a_h,deriv=True)
  fs=dEdah*dahdzh
  dEdw1=np.dot(dzhdw.T,fs)
  #Weight Update
  w1=w1-(eta*dEdw1)
 
print(w1)
print(w2)
  

[[ 0.32258295  0.06464222  0.27082314 -0.02078038  1.13708281  0.76089158
  -0.62150535  1.05266335]
 [ 0.22763589  0.43874688  4.2526551  -1.3118715   0.7445326   0.28773296
   1.05659063  0.53235323]
 [ 1.0941973   0.23010179 -0.31895168  0.18031713  0.29478761  0.42045646
  -0.16054244 -0.10494449]
 [-0.37870922  0.67093304  2.08686782 -0.48596457  0.12715237  0.78659087
   1.14837494 -0.47790627]
 [ 0.31614566  0.71376236  5.46294425 -1.91396645 -0.35904294  0.35785738
   1.18780354 -0.5979681 ]
 [ 0.64612951  0.53443172 -0.40576832  0.01208439  1.18918916  0.94298372
   0.07736656  0.82432354]
 [ 0.98272958  0.9321454  -4.93346148  1.71813196  0.92630854  0.10549657
   0.66012222  1.13347942]
 [ 0.16281924  0.1886507  -1.92532268  0.64614625  0.80295511  0.5222129
   0.74750893  1.11440268]
 [ 0.77685295  0.87141842 -3.60756026  1.38681971 -0.04745993  0.77876827
  -0.06001227 -0.23295362]
 [ 0.42366336  0.71363135  0.28729725  0.03711271  0.1435194   0.78890197
   0.3698615   0.6

In [52]:
np.set_printoptions(suppress=True)
test_ah=sigmoid(np.dot(X,w1))
prediction=sigmoid(np.dot(test_ah,w2))
print(prediction)

[[ 0.0001563   0.00016476  0.00064668]
 [ 0.0002266   0.00027588  0.99837223]
 [ 0.00016074  0.00016087  0.00256728]
 [ 0.00063294  0.00064343  0.00131178]
 [ 0.00025387  0.00030787  0.99871088]
 [ 0.00025159  0.00030703  0.99818144]
 [ 0.00016466  0.00015627  0.00219113]
 [ 0.00082348  0.00074823  0.99807502]
 [ 0.00021597  0.00027072  0.99829813]
 [ 0.00052541  0.00047792  0.99978278]]


In [55]:
result=[]
for i in range(0,10):
    tp=[]
    for j in range(0,3):
        if(prediction[i][j]>0.90):
            tp.append(1)
        else:
            tp.append(0)
    result.append(tp)
target=np.reshape(result,(10,3))
print(target)

[[0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]]


In [57]:
#Training Accuracy
cnt=0

for i in range(0,10):
    for j in range(0,3):
        if(target[i][j]==y[i][j]):
            cnt=cnt+1

accuracy=(cnt/30.00)*100.00
print(accuracy,"%")
    
        

100.0 %
