In [2]:
import numpy as np

In [45]:

data=np.random.randint(2,size=(100,10))
#print(data)
#extra=np.ones((100,1),dtype=int)
#print(extra)
X=data
#X= np.concatenate((data, extra), axis=1)
print(X)

[[1 0 0 1 0 0 0 1 1 0]
 [1 1 1 0 1 0 0 1 1 0]
 [1 0 1 0 1 1 0 0 0 1]
 [1 1 1 0 0 1 1 0 0 0]
 [0 0 1 1 1 1 0 1 1 0]
 [0 0 1 1 0 1 1 0 0 0]
 [1 1 0 0 0 0 0 0 0 1]
 [0 0 1 1 0 0 1 0 1 1]
 [1 1 0 1 0 0 0 1 1 0]
 [1 1 1 0 0 1 1 0 0 1]
 [0 0 1 0 1 1 0 1 1 0]
 [0 0 1 1 0 1 0 1 1 1]
 [0 0 1 1 1 0 0 1 1 0]
 [0 1 1 0 1 0 1 0 1 1]
 [1 1 0 1 0 1 0 0 0 1]
 [1 0 0 0 0 0 1 1 0 1]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 1 1]
 [1 1 1 0 0 0 0 0 0 0]
 [1 0 0 1 1 1 1 1 0 1]
 [0 1 0 1 0 0 1 1 1 1]
 [0 1 1 0 0 0 1 0 1 0]
 [1 1 0 0 0 0 1 1 0 0]
 [1 0 1 0 0 0 0 1 0 0]
 [0 0 1 1 0 1 1 1 1 0]
 [1 0 0 1 1 1 0 1 0 0]
 [0 1 1 1 0 0 0 1 0 0]
 [0 1 1 1 1 0 0 1 0 0]
 [0 1 1 0 0 1 1 0 1 0]
 [1 0 1 0 0 1 0 1 0 0]
 [1 0 0 1 1 0 1 0 0 0]
 [1 0 0 0 0 0 1 0 1 0]
 [1 0 1 0 0 0 1 0 0 0]
 [0 0 1 0 1 1 1 1 0 0]
 [1 1 0 1 0 0 1 1 0 1]
 [1 0 0 1 0 1 1 0 0 1]
 [1 1 1 0 1 1 1 1 1 0]
 [1 1 0 0 0 0 0 1 1 0]
 [1 0 1 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 0 0 1 1]
 [0 0 1 1 0 1 0 1 1 0]
 [1 0 1 1 0 1 1 1 1 0]
 [0 0 0 1 1 0 0 1 0 0]
 [1 0 0 1 0

In [46]:
ans=[]
for i in range(0,100):
  res=0
  for j in range(0,10):
      #print((X[i][j]), end = '')
      res=abs(X[i][j]-res)
  #print("")
  ans.append(res)
y=np.reshape(ans,(100,1))
print(y)
      

[[0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]]


In [47]:
w1=np.random.random((10,5))
w2=np.random.random((5,1))
print(w1)
print(w2)

[[ 0.85798742  0.46308227  0.65589758  0.5269223   0.85826291]
 [ 0.50236498  0.96425838  0.06594981  0.66144263  0.4476033 ]
 [ 0.58507367  0.21873226  0.4929727   0.00080853  0.21193977]
 [ 0.62188537  0.52971707  0.43481387  0.66760577  0.53634946]
 [ 0.56284877  0.03929565  0.10217169  0.99663742  0.44384185]
 [ 0.83256666  0.71369239  0.57200527  0.59922103  0.30844375]
 [ 0.22476877  0.02283874  0.60519163  0.03693896  0.23578732]
 [ 0.27375614  0.19206289  0.87084719  0.04667994  0.44842508]
 [ 0.19793348  0.80386307  0.04949142  0.6470602   0.04529489]
 [ 0.61195712  0.63182626  0.18455602  0.66781225  0.33206238]]
[[ 0.6549628 ]
 [ 0.98611526]
 [ 0.10586247]
 [ 0.10487544]
 [ 0.94641609]]


In [48]:
b1=np.ones((10,5))
b2=np.ones((5,1))
w1=w1+b1
w2=w2+b2
print(w1)
print(w2)

[[ 1.85798742  1.46308227  1.65589758  1.5269223   1.85826291]
 [ 1.50236498  1.96425838  1.06594981  1.66144263  1.4476033 ]
 [ 1.58507367  1.21873226  1.4929727   1.00080853  1.21193977]
 [ 1.62188537  1.52971707  1.43481387  1.66760577  1.53634946]
 [ 1.56284877  1.03929565  1.10217169  1.99663742  1.44384185]
 [ 1.83256666  1.71369239  1.57200527  1.59922103  1.30844375]
 [ 1.22476877  1.02283874  1.60519163  1.03693896  1.23578732]
 [ 1.27375614  1.19206289  1.87084719  1.04667994  1.44842508]
 [ 1.19793348  1.80386307  1.04949142  1.6470602   1.04529489]
 [ 1.61195712  1.63182626  1.18455602  1.66781225  1.33206238]]
[[ 1.6549628 ]
 [ 1.98611526]
 [ 1.10586247]
 [ 1.10487544]
 [ 1.94641609]]


In [49]:
def sigmoid(x, deriv=False):
  if(deriv):
    return x*(1-x)
  else:
    return (1/(1+np.exp(-x)))

In [50]:
for epoch in range(0,80000):
  
  eta=0.5
  #Weighted Sum

  z_h=np.dot(X,w1)
  a_h=sigmoid(z_h)
  
  # second weighted sum
  z_o=np.dot(a_h,w2)
  a_o=sigmoid(z_o)
  #Error Calculate
  Ea=(0.5*(np.power((a_o-y),2)))
  #BackPropagation dE/dw2
  #dE/da0
  dEda0=(a_o-y)
  #da0/dz0
  da0dz0=sigmoid(a_o,deriv=True)
  #dz0/dw
  dz0dw=a_h
  #dE/dw2
  st=da0dz0*dEda0
  dEdw2=np.dot(dz0dw.T,st)
  #Weight update
  w2=w2-(eta*dEdw2)
  #hidden Layer dEdw1
  #dE/dah
  dEdah=np.dot(st,w2.T)
  #dzh/dw
  dzhdw=X
  #dah/dzh
  dahdzh=sigmoid(a_h,deriv=True)
  fs=dEdah*dahdzh
  dEdw1=np.dot(dzhdw.T,fs)
  #Weight Update
  w1=w1-(eta*dEdw1)
 
print(w1)
print(w2)
  

[[ -5.19026075   8.52983881   9.45204579  10.92066192   7.91885845]
 [ -2.81982092   9.06471217   8.86932304  -7.44001289   8.7748323 ]
 [  3.46858544   8.30104547  -7.13466114  -7.30446551  -8.70721833]
 [-11.03867123  -9.27321505   6.84878833   9.38289222   7.75638396]
 [  5.74316536   8.70362129  -7.87352153  -9.73923886  -9.15251499]
 [ -6.98598726   8.99240227   4.66557002 -10.12964518  -9.2700995 ]
 [  1.29765753  -8.67818142   5.86033043  10.18655269   8.88810755]
 [  9.77993819  -8.97677321  -5.47210507  -8.20263675   8.14240557]
 [ -0.63016281   8.8148679    9.83524642   8.98948803   8.10876007]
 [ -5.03155476   7.91167182  -5.02208553  25.79026718  -9.17039501]]
[[-24.47637224]
 [ 28.98233217]
 [-36.44315434]
 [ -8.27666459]
 [ 28.51789844]]


In [51]:
np.set_printoptions(suppress=True)
test_ah=sigmoid(np.dot(X,w1))
prediction=sigmoid(np.dot(test_ah,w2))
print(prediction)

[[ 0.00037938]
 [ 0.03224377]
 [ 1.        ]
 [ 1.        ]
 [ 0.00005699]
 [ 0.        ]
 [ 0.99999714]
 [ 0.99999703]
 [ 0.99999716]
 [ 0.0000202 ]
 [ 0.98804766]
 [ 0.00000113]
 [ 1.        ]
 [ 0.        ]
 [ 0.99999698]
 [ 0.        ]
 [ 0.99456021]
 [ 0.99999713]
 [ 1.        ]
 [ 0.99999661]
 [ 0.00010434]
 [ 0.00162059]
 [ 0.        ]
 [ 1.        ]
 [ 0.00066687]
 [ 1.        ]
 [ 0.00147593]
 [ 1.        ]
 [ 1.        ]
 [ 0.0000002 ]
 [ 0.00122619]
 [ 0.99999632]
 [ 0.95655671]
 [ 0.98899715]
 [ 0.0000257 ]
 [ 0.99999695]
 [ 0.03952451]
 [ 0.0035085 ]
 [ 0.00065711]
 [ 0.00000715]
 [ 1.        ]
 [ 0.99999714]
 [ 0.98561026]
 [ 0.99999713]
 [ 0.99999685]
 [ 0.99818278]
 [ 0.98868752]
 [ 0.99999708]
 [ 0.99999704]
 [ 0.99999701]
 [ 0.00006635]
 [ 0.00086525]
 [ 0.95187849]
 [ 0.00000867]
 [ 0.99335969]
 [ 0.00000607]
 [ 1.        ]
 [ 0.99999703]
 [ 0.00000078]
 [ 0.999997  ]
 [ 0.00021148]
 [ 0.        ]
 [ 0.99999688]
 [ 0.99167401]
 [ 0.99639651]
 [ 0.00000079]
 [ 0.00177

In [52]:
result=[]
for i in range(0,100):
    if(prediction[i]>0.90):
        result.append(1)
    else:
        result.append(0)
target=np.reshape(result,(100,1))
print(target)

[[0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]]


In [53]:
#Training Accuracy
cnt=0

for i in range(0,100):
    for j in range(0,1):
        if(target[i][j]==y[i][j]):
            cnt=cnt+1

accuracy=(cnt/100)*100.00
print(accuracy,"%")
    
        

100.0 %


In [54]:
#Testing Data set
tdata=np.random.randint(2,size=(100,10))
#print(data)
#textra=np.ones((100,1),dtype=int)
#print(extra)
#test_X= np.concatenate((tdata, textra), axis=1)
test_X=tdata
print(test_X)


[[0 0 0 1 1 1 0 1 0 1]
 [0 1 1 1 0 0 0 1 1 0]
 [1 1 1 1 1 0 0 0 0 0]
 [0 1 1 1 0 1 0 1 0 1]
 [0 1 1 1 1 1 0 1 1 1]
 [0 0 1 1 0 1 0 1 1 1]
 [1 1 1 1 0 0 1 1 0 0]
 [0 1 1 0 0 0 1 0 0 1]
 [1 0 0 0 1 1 1 1 0 0]
 [0 1 1 0 0 1 0 0 1 0]
 [1 0 1 0 0 1 0 0 1 0]
 [1 1 1 0 1 1 0 1 0 1]
 [1 0 0 0 1 0 0 0 1 0]
 [1 1 0 0 0 1 1 1 1 1]
 [1 1 0 1 0 1 0 1 0 1]
 [0 0 1 1 0 1 1 1 1 1]
 [1 0 0 0 1 1 0 0 0 1]
 [0 1 1 1 1 1 0 0 1 1]
 [0 0 0 0 0 1 0 1 1 1]
 [1 0 0 1 0 1 1 1 1 1]
 [1 0 1 1 1 0 1 1 0 1]
 [1 0 0 1 1 1 1 0 0 0]
 [1 1 1 0 1 0 1 0 1 1]
 [0 0 0 1 1 0 0 0 1 1]
 [1 0 1 0 1 0 0 0 0 1]
 [1 1 1 1 1 1 1 0 1 0]
 [0 1 0 0 1 1 0 0 1 1]
 [0 1 0 0 0 1 0 0 1 1]
 [0 1 0 1 1 0 1 0 1 0]
 [1 1 1 1 0 0 1 1 0 1]
 [1 1 1 0 0 0 0 1 0 0]
 [1 1 0 0 1 0 0 1 0 0]
 [0 1 1 1 1 0 0 1 0 1]
 [0 1 1 0 0 1 0 1 0 1]
 [0 0 0 0 1 1 1 0 1 0]
 [1 1 1 0 1 1 1 1 1 0]
 [0 0 1 1 1 1 1 1 0 1]
 [1 0 1 1 1 0 0 1 1 1]
 [1 0 1 0 1 0 1 0 1 1]
 [0 1 1 1 1 0 1 1 0 0]
 [0 1 0 1 0 1 0 1 1 1]
 [0 1 0 0 1 1 0 0 1 1]
 [0 0 0 0 1 1 0 1 1 1]
 [0 1 1 1 0

In [55]:
tans=[]
for i in range(0,100):
  tres=0
  for j in range(0,10):
      #print((X[i][j]), end = '')
      tres=abs(test_X[i][j]-tres)
  #print("")
  tans.append(tres)
test_y=np.reshape(tans,(100,1))
print(test_y)

[[1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]]


In [56]:
np.set_printoptions(suppress=True)
test_p=sigmoid(np.dot(test_X,w1))
test_prediction=sigmoid(np.dot(test_p,w2))
print(test_prediction)

[[ 1.        ]
 [ 0.99999981]
 [ 1.        ]
 [ 0.00002935]
 [ 0.0000025 ]
 [ 0.00000113]
 [ 0.00014258]
 [ 0.18399586]
 [ 0.03941985]
 [ 0.41867358]
 [ 0.00000969]
 [ 1.        ]
 [ 0.72830223]
 [ 0.99999718]
 [ 0.99999718]
 [ 0.99999684]
 [ 0.00058466]
 [ 0.00000015]
 [ 0.00000133]
 [ 0.99999713]
 [ 1.        ]
 [ 0.99999699]
 [ 0.99999211]
 [ 0.00000311]
 [ 0.9999993 ]
 [ 0.99999736]
 [ 0.00000015]
 [ 0.00002096]
 [ 0.99999713]
 [ 0.99999709]
 [ 0.04029775]
 [ 0.04085183]
 [ 0.9999824 ]
 [ 1.        ]
 [ 0.00000136]
 [ 0.03952451]
 [ 1.        ]
 [ 1.        ]
 [ 0.        ]
 [ 0.00000045]
 [ 0.99999718]
 [ 0.00000015]
 [ 0.03914583]
 [ 0.        ]
 [ 1.        ]
 [ 0.00000442]
 [ 0.04550504]
 [ 0.00000867]
 [ 0.01652743]
 [ 0.99999724]
 [ 1.        ]
 [ 0.00000015]
 [ 0.99999705]
 [ 0.        ]
 [ 0.00009215]
 [ 1.        ]
 [ 0.0000202 ]
 [ 0.99999731]
 [ 0.98891109]
 [ 0.00021148]
 [ 0.11982973]
 [ 0.02874805]
 [ 0.62480444]
 [ 0.99999896]
 [ 0.00000125]
 [ 0.00000046]
 [ 0.00000

In [57]:
tresult=[]
for i in range(0,100):
    if(test_prediction[i]>0.90):
        tresult.append(1)
    else:
        tresult.append(0)
test_target=np.reshape(tresult,(100,1))
print(test_target)

[[1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]]


In [58]:
#Testing Accuracy
tcnt=0

for i in range(0,100):
    for j in range(0,1):
        if(test_target[i][j]==test_y[i][j]):
            tcnt=tcnt+1

taccuracy=(tcnt/100)*100.00
print(taccuracy,"%")
    

65.0 %
